### ISSUE TITLE
Mod loader once again loading mods that shouldn't be enabled

### ISSUE THREAD

**Issue by dancaiman** [X-Hax/SA-Mod-Manager#259] opened 2024-12-03 20:15 UTC
**Describe the bug**
mod loader loads mods that are not selected and ignores mods that were selected to be enabled,

**To Reproduce**
I don't remember the exact same steps I did, but I do remember that a common nominator was enabling the "maintain mod order" for all the instances this happened

**Expected behavior**
The loader will act as if you had a configuration that you had previously, but that now is modified and should not load the mods that it does

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I made an entry a few days ago, (which no one bothered to look into) in which I talked about how my mod loader was loading with mods that were not selected, and not loading with the mods that were selected, this issue seemed to be solved after leaving the loader alone for some time but here it is again, once again this happened with Sonic adventure 2

**Comment by Sora-yx** [comment] 2024-12-03 22:37
We had similar report recently, but we are not sure what is up with that at all since that seemed very random.
Can you open your current Manager Profile in `AppData -> Local -> SAManager -> SA2` and check if you have  a  **ModsList** saved (should be below **EnabledMods**). If so, can you check if it's loading this list instead of the EnabledMods?

**Comment by dancaiman** [comment] 2024-12-03 23:45
I went to app data and these are the document I have, which are the files of the profiles I made in the SA2 section except for one of them, so I went to the folders where my manager is located (I have it on both my Sonic adventure 1 and 2 steam folder) and I found that there is a SAManager folder (like you mentioned) only on my Sonic adventure 1 which is weird because I've been having these problems with SA2, and I saw that inside the SA2 folder there was the profile that was missing in the Appdata folder, could It be that both of them are conflicting, is the problem that I have various profiles, or is the issue on one of the files in the Appdata folder that I didn't notice? for now I'll delete the SAmanager folder from the SA1 steam folder and update you if that achieves something, thanks for reaching out to help

**Comment by dancaiman** [comment] 2024-12-04 00:14
Ok so I just tried deleting the folder from SA1 steam and, thankfully that seemed to fix all the issues, I've been trying checked and unchecking mods and now it works flawlessly, so knowing that the SAmanager folder was the root of the problem, how do I prevent it from reappearing?

Also this is very off topic but I was pretty surprised to see that it was you the one that offered help for my problem since you're one of my favourite sonic modders, and I feel like this is taking advantage of the privilage of talking to you directly, but I wanted to let you know that the Amy's new tricks mod you did for SA2 (wonderful btw) has a huge issue with the Character select plus mod, since when selecting Sonic, it justs acts like you've selected amy, and selecting amy will just load the level with her too so there's no way to play with Sonic if you don't close the game and deactivate the mod, I know how hard programming must be and I'm expecting you to put extra work on a 2 year old mod, but If you knew this issue or have any Idea of what may be causing it (my guess is that it originates from the fact that Amy replaces Sonic when you got the mod active on the vanilla game) Do you know some workaround to this issue?

Once again I'm sorry for overstepping my bounds but I really enjoy that mod and it would be more comfortable if it were to be fixed. Thanks so much for the help

**Comment by PiKeyAr** [comment] 2024-12-04 11:04
> knowing that the SAmanager folder was the root of the problem, how do I prevent it from reappearing?


This folder is only written to if it already exists, so the Manager won't recreate it. However, at the moment the SADX Mod Installer creates it by default to make the Mod Manager work in "portable mode" with SADX. This may be changed in later updates.

Normally, the Manager looks for the SAManager folder next to its EXE first, and if it doesn't exist, then it uses the one in AppData\Local. What I suspect happened here was that at some point SAManager.exe was executed outside of the SADX folder, and now there are SAManager folders both in the SADX folder and in AppData\Local. That, or there's some issue with handling these paths while running in SA2 mode.

**Comment by PiKeyAr** [comment] 2024-12-04 13:27
As of Build 47, SADX Mod Installer should put the Manager's data in local AppData. It will also clean up the SAManager folder in the game folder if it exists.

**Comment by ItsEasyActually** [comment] 2024-12-04 14:54
Closing this as the issue is resolved. Make sure that the SAManager folder is deleted if it's in a folder next to the SA Mod Manager executable. Situation basically boiled down to the Mod Manager saving settings elsewhere than the settings folder the game was trying to use.

**Closed by ItsEasyActually** 2024-12-04 14:54 UTC
Labels: bug
